<?php

use Modules\Superadmin\Entities\Package;

use Illuminate\Database\Seeder;

class PackageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [

                "name" => "نسخة تجريبية",
                "description" => "حزمة تجربية لمدة 10 أيام",
                "location_count" => 0,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'days',
                "interval_count" => 10,
                'trial_days' => 10,
                'price' => 0.0000,
                'custom_permissions' => '{"manufacturing_module":"1","repair_module":"1"}',
                'created_by' => 3,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 1,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],
            [

                "name" => "Gold",
                "description" => "للشركات و المطاعم و الكافيهات المتوسطه و مراكز الصيانه - اول شهر مجانا جربه الان",
                "location_count" => 3,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'months',
                "interval_count" => 1,
                'trial_days' => 10,
                'price' => 70.0000,
                'custom_permissions' => '{"essentials_module":"1","productcatalogue_module":"1","woocommerce_module":"1"}',
                'created_by' => 1,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],

            [

                "name" => "Silver",
                "description" => "للشركات الصغرى و المطاعم و الكافيهات - اول شهر مجانا جربه الان",
                "location_count" => 2,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'months',
                "interval_count" => 1,
                'trial_days' => 10,
                'price' => 50.0000,
                'custom_permissions' => '{"essentials_module":"1","woocommerce_module":"1"}',
                'created_by' => 1,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],


            [

                "name" => "نسخة المحل الواحد متقدمة",
                "description" => "إدارة مبيعات - مشتريات - مخازن - حسابات - ضرائب - مطاعم",
                "location_count" => 1,
                "user_count" => 10,
                "product_count" => 2000,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 2147483647,
                "interval" => 'months',
                "interval_count" => 1,
                'trial_days' => 10,
                'price' => 40.0000,
                'custom_permissions' => '',
                'created_by' => 1,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],
            [

                "name" => "نسخة المحل الواحد",
                "description" => "إدارة مبيعات - مشتريات - مخازن - حسابات - ضرائب - مطاعم	مفتوحة",
                "location_count" => 1,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'months',
                "interval_count" => 1,
                'trial_days' => 30,
                'price' => 20.0000,
                'custom_permissions' => '',
                'created_by' => 1,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],

            [
                "name" => "نسخه تجريبيه",
                "description" => "للشركات و المصانع الكبرى و ادارة المشروعات وجميع الانشطه التجاريه",
                "location_count" => 0,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'months',
                "interval_count" => 1,
                'trial_days' => 10,
                'price' => 0.0000,
                'custom_permissions' => '{"woocommerce_module":"1","productcatalogue_module":"1","essentials_module":"1","crm_module":"1","repair_module":"1","installment_module":"1","manufacturing_module":"1","ChartofAccounts":"1","inventory_module":"1","GeneralAccount":"1","tracker_module":"1","project_module":"1"}',
                'created_by' => 1,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 1,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],
            [
                "name" => "all module",
                "description" => "all",
                "location_count" => 0,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'days',
                "interval_count" => 7,
                'trial_days' => 7,
                'price' => 150.0000,
                'custom_permissions' => '{"Assets_module":"1","crm_module":"1","essentials_module":"1","manufacturing_module":"1","partners_module":"1","project_module":"1","repair_module":"1","woocommerce_module":"1"}',
                'created_by' => 3,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 1,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],


            [
                "name" => "نسخه سوبر ماركت",
                "description" => "للسوبر ماركت والهايب ر ماركت حيث انها توفر",
                "location_count" => 10,
                "user_count" => 0,
                "product_count" => 0,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 0,
                "interval" => 'years',
                "interval_count" => 365,
                'trial_days' => 10,
                'price' => 150.0000,
                'custom_permissions' => '{"essentials_module":"1","partners_module":"1","project_module":"1","repair_module":"1"}',
                'created_by' => 3,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],
            
            [
                "name" => "للتصنيع",
                "description" => "للتصنيع والصانع",
                "location_count" => 1,
                "user_count" => 1,
                "product_count" => 1000,
                'bookings' => 0,
                'kitchen' => 0,
                'order_screen' => 0,
                'tables' => 0,
                "invoice_count" => 1000,
                "interval" => 'days',
                "interval_count" => 30,
                'trial_days' => 10,
                'price' => 0.0000,
                'custom_permissions' => '{"partners_module":"1","repair_module":"1","installment_module":"1","manufacturing_module":"1","GeneralAccount":"1","tracker_module":"1","project_module":"1"}',
                'created_by' => 3,
                'sort_order' => 1,
                'is_active' => 1,
                'is_private' => 0,
                'is_one_time' => 0,
                'enable_custom_link' => 0,
                'custom_link' => null,
                'custom_link_text' => null,
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
                // 'enabled_modules'=>null
            ],



        ];

        Package::insert($data);
    }
}
