<?php

namespace Modules\Tracker\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @method static select(string[] $array)
 */
class Province extends Model
{
    use HasFactory;

    protected $table = 'dm_provinces';

    protected $fillable = ['name', 'phone', 'description', 'business_id', 'user_id'];

    protected static function newFactory()
    {
        return \Modules\Tracker\Database\factories\ProvinceFactory::new();
    }


    public function resolveRouteBindingQuery($query, $value, $field = null)
    {
        return parent::resolveRouteBindingQuery($query, $value, $field)->where('business_id', session()->get('user.business_id')); // TODO: Change the autogenerated stub
    }
}
